name: Haystack 1.x Benchmarks

on:
  workflow_dispatch:
  schedule:
    # At 00:01 on Saturday
    - cron: "1 0 * * 6"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    outputs:
      cml_runner_id: ${{ steps.deploy.outputs.cml_runner_id }}
    steps:
      - uses: actions/checkout@v4

      - uses: iterative/setup-cml@v2

      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}

      - name: Launch EC2 instance and deploy runner
        id: deploy
        env:
          repo_token: ${{ secrets.HAYSTACK_BOT_TOKEN }}
        run: |
          OUTPUT=$(cml runner launch \
          --cloud aws \
          --cloud-region ${{ env.AWS_REGION }} \
          --cloud-type=p3.2xlarge \
          --cloud-hdd-size=64 \
          --labels=cml 2>&1 | tee /dev/fd/2)
          # Extract 'id' from the log and set it as an environment variable
          ID_VALUE=$(echo "$OUTPUT" | jq -r '.message? | fromjson? | select(.id != null) | .id // empty')
          echo "cml_runner_id=$ID_VALUE" >> "$GITHUB_OUTPUT"
  

  run-elasticsearch-benchmarks:
    needs:
      - deploy-runner
    runs-on: [self-hosted, cml]
    container:
      image: docker://iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    services:
      elasticsearch:
        image: elasticsearch:7.17.6
        env:
          discovery.type: "single-node"
        ports:
          - 9201:9200
    timeout-minutes: 2880

    steps:
      - uses: actions/checkout@v4

      - name: Install Haystack + Datadog requirements
        run: |
          pip install -e '.[dev]' 
          pip install elasticsearch-haystack datadog==0.45.0

      - name: Run benchmarks
        working-directory: test/benchmarks
        run: |
          mkdir +p out
          echo "=== Running indexing/retrieval on Elasticsearch benchmarks  ===";
          config_name="indexing_retrieval"
          python indexing_retrieval.py;
          echo "=== Benchmarks done for indexing/retrieval on Elasticsearch (or failed) ===";


      - name: Send Benchmark results to Datadog
        working-directory: test/benchmarks
        run: |
          python datadog/send_metrics.py out/ ${{ secrets.CORE_DATADOG_API_KEY }} https://api.datadoghq.eu

      - name: Archive benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results-elasticsearch
          path: test/benchmarks/out/

  terminate-runner:
    if: always()
    needs:
      - deploy-runner
      - run-elasticsearch-benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}

      - name: Terminate EC2 instance
        env:
          CML_RUNNER_ID: ${{needs.deploy-runner.outputs.cml_runner_id}}
        run: |
          # Get the instance ID using its Name tag and terminate the instance
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ env.CML_RUNNER_ID }}" --query "Reservations[*].Instances[*].[InstanceId]" --output text)
          aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"